#!/usr/bin/env python
#
# -*- coding: UTF-8 -*-
#
# generated by wxGlade HG on Tue Jan  8 19:11:21 2013
# manual improvements done
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.frameStatusbar = self.CreateStatusBar(3, 0)
        global ID_DRAW; ID_DRAW = wx.NewId()
        self.drawPanel = wx.Panel(self, ID_DRAW)

        global ID_TIMER; ID_TIMER = wx.NewId()
        self.timer = wx.Timer(self, ID_TIMER)

        # Menu Bar
        self.frameMenubar = wx.MenuBar()
        global ID_PAUSE; ID_PAUSE = wx.NewId()
        self.menuFile = wx.Menu()
        self.itemNew = wx.MenuItem(self.menuFile, wx.ID_NEW, "New Game",
            "Start a new game", wx.ITEM_NORMAL)
        self.menuFile.AppendItem(self.itemNew)
        self.itemPause = wx.MenuItem(self.menuFile, ID_PAUSE, "Pause",
            "Pause the current game", wx.ITEM_NORMAL)
        self.itemPause.Enable(False)
        self.menuFile.AppendItem(self.itemPause)
        self.menuFile.AppendSeparator()
        self.itemExit = wx.MenuItem(self.menuFile, wx.ID_EXIT, "Quit",
            "Quit the game", wx.ITEM_NORMAL)
        self.menuFile.AppendItem(self.itemExit)
        self.frameMenubar.Append(self.menuFile, "File")
        self.SetMenuBar(self.frameMenubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Tetris with wxPython")
        self.SetSize((260, 600))
        self.frameStatusbar.SetStatusWidths([-1, 80, 100])
        # statusbar fields
        frameStatusbar_fields = ["Game over", "Next tile: -", "Points: 0 (1)"]
        for i in range(len(frameStatusbar_fields)):
            self.frameStatusbar.SetStatusText(frameStatusbar_fields[i], i)
        self.drawPanel.SetBackgroundColour(wx.Colour(0, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.drawPanel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade

# end of class MainFrame
if __name__ == "__main__":
    app = wx.App(0)
    frame = MainFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame)
    frame.Show()
    app.MainLoop()